import "./globals.css";
import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import Header from "@/components/layout/header/Header";
import Providers from "@/providers";
import React from "react";
import Sidebar from "@/components/layout/sidebar/components/sidebar";
import {getAuth} from "@/features/auth/authActions";
import RedirectToaster from "@/components/shared/RedirectToaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
                                           children,
                                         }: Readonly<{
  children: React.ReactNode;
}>) {

  const {user} = await getAuth()

  return (

    <html lang="en" suppressHydrationWarning className="h-full">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
    >
    <Providers>

      <header className="border-b-slate-100 border-b-1">
        <Header/>
      </header> 
      <div>
        {
          user ? <Sidebar/> : <div className="w-[78px]"></div>
        }
        <main className="max-w-4/5 mx-auto pt-5 h-[calc(100%-63px)]">
          {children}
        </main>
      </div>            
    </Providers>
    </body>
    </html>
  )
}
