import "./globals.css";
import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <header className="border-b-slate-100 border-b-1">
      <nav className="flex justify-between p-2 max-w-4/5 mx-auto ">
        <Link href="/">Home</Link>
        <Link href="/tickets">Tickets</Link>
      </nav>
    </header>
    <main className="max-w-4/5 mx-auto pt-5">
      {children}
    </main>
    </body>
    </html>
  );
}
