import "./globals.css";
import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import Header from "@/components/layout/Header";
import Providers from "@/providers";
import React from "react";
import RedirectToaster from "@/components/shared/RedirectToaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en" suppressHydrationWarning>

    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >

    <Providers>
      <header className="border-b-slate-100 border-b-1">
        <Header/>
      </header>
      <main className="max-w-4/5 mx-auto pt-5">
        {children}
      </main>
    </Providers>
    <RedirectToaster />
    </body>
    </html>
  )
}
